name: Build GAROU Audio

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          add-to-path: true

      - name: Build libgarou_audio.so
        run: |
          ndk-build \
            NDK_PROJECT_PATH="$GITHUB_WORKSPACE" \
            APP_BUILD_SCRIPT="$GITHUB_WORKSPACE/jni/Android.mk" \
            NDK_APPLICATION_MK="$GITHUB_WORKSPACE/jni/Application.mk" \
            -j2

      - name: Upload SO files
        uses: actions/upload-artifact@v4
        with:
          name: libgarou_audio
          path: |
            libs/**/libgarou_audio.so
